# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'information_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_user_info(object):
    def setupUi(self, user_info):
        user_info.setObjectName("user_info")
        user_info.resize(640, 480)
        user_info.setMinimumSize(QtCore.QSize(640, 480))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        user_info.setWindowIcon(icon)
        user_info.setStyleSheet("font: 8pt \"Consolas\";")
        self.verticalLayout = QtWidgets.QVBoxLayout(user_info)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEdit = QtWidgets.QTextEdit(user_info)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.error = QtWidgets.QLabel(user_info)
        self.error.setText("")
        self.error.setObjectName("error")
        self.verticalLayout.addWidget(self.error)

        self.retranslateUi(user_info)
        QtCore.QMetaObject.connectSlotsByName(user_info)

    def retranslateUi(self, user_info):
        _translate = QtCore.QCoreApplication.translate
        user_info.setWindowTitle(_translate("user_info", "Информация о пользователе"))
