# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'management_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_user_management(object):
    def setupUi(self, user_management):
        user_management.setObjectName("user_management")
        user_management.resize(320, 320)
        user_management.setMinimumSize(QtCore.QSize(320, 320))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        user_management.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(user_management)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(user_management)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 8, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(user_management)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 4, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(user_management)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 9, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(user_management)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 6, 1, 1, 1)
        self.line = QtWidgets.QFrame(user_management)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 7, 1, 1, 2)
        self.pushButton = QtWidgets.QPushButton(user_management)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(user_management)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(user_management)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 10, 1, 1, 1)
        self.label = QtWidgets.QLabel(user_management)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 1, 1, 1)
        self.error = QtWidgets.QLabel(user_management)
        self.error.setMaximumSize(QtCore.QSize(16777215, 10))
        self.error.setText("")
        self.error.setObjectName("error")
        self.gridLayout.addWidget(self.error, 11, 1, 1, 1)

        self.retranslateUi(user_management)
        QtCore.QMetaObject.connectSlotsByName(user_management)

    def retranslateUi(self, user_management):
        _translate = QtCore.QCoreApplication.translate
        user_management.setWindowTitle(_translate("user_management", "Управление пользователем"))
        self.label_2.setText(_translate("user_management", "Переместить пользователя в группу"))
        self.lineEdit_2.setPlaceholderText(_translate("user_management", "Название группы (без кавычек)"))
        self.pushButton_3.setText(_translate("user_management", "Поиск"))
        self.pushButton.setText(_translate("user_management", "Заблокировать пользователя"))
        self.pushButton_2.setText(_translate("user_management", "Разблокировать пользователя"))
        self.pushButton_4.setText(_translate("user_management", "Переместить"))
        self.label.setText(_translate("user_management", "Найти машину с которой был заблокирован пользователь"))
